[package]
name = "mal_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rustyline = { version = "17.0.2", features = ["with-file-history"] }

[[bin]]
name = "step0_repl"
path = "step0_repl.rs"
